[package]
name = "restate-opendal"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
content_disposition = "0.4.0"
futures = "0.3"
http = "1.4.0"
humantime-serde = { workspace = true }
jiff = "0.2.19"
opendal = { workspace = true, features = ["services-memory"] }
opendal-util = { workspace = true }
pastey = "0.2"
restate-sdk = { workspace = true, features = ["hyper", "schemars"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-path = "0.12.3"
url = { workspace = true }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
# ctor 1.0.8+ produces misaligned Mach-O sections on arm64 macOS.
ctor = "=1.0.11"
